# Generated by Django 5.2 on 2025-04-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default=9563247851, max_length=15),
            preserve_default=False,
        ),
    ]
